ports:
  - port: 8080 # airflow UI
    onOpen: notify
image:
  file: .gitpod.Dockerfile
tasks:
  - name: setup
    init: |
      mkdir 2_workflows/airflow/workspace/mount/logs 2_workflows/airflow/workspace/mount/plugins
      sudo chmod -R 777 2_workflows/airflow/workspace
      sudo chmod -R 777 2_workflows/rabbitmq/workspace
      mkdir 4_apache_storm/storm-supervisor/logs
      sudo chmod -R 777 apache_storm
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
