version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./workspace/rabbitmq/data/:/var/lib/rabbitmq/
      - ./workspace/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  producer:
    build: .
    container_name: "producer"
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge